# Generated by Django 5.1.3 on 2024-11-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriTech', '0003_rename_region_agriculteur_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculteur',
            name='location',
            field=models.CharField(default='Valeur par défaut', max_length=255),
        ),
    ]
