# Generated by Django 5.1.3 on 2024-11-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriTech', '0004_alter_agriculteur_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculteur',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AgriTech.customuser'),
        ),
    ]
