# Generated by Django 5.1.3 on 2024-11-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgriTech', '0005_alter_agriculteur_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='agriculteur',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='operateur',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='suividestock',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Agriculteur',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Operateur',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='SuiviDeStock',
        ),
    ]
