# Generated by Django 5.1.3 on 2024-11-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriTech', '0007_agriculteur_remove_produit_nom_remove_produit_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
