# Generated by Django 5.1.3 on 2024-11-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriTech', '0008_alter_produit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
