# Generated by Django 5.1.3 on 2024-11-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgriTech', '0009_alter_produit_created_at'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='produit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
    ]
