# Generated by Django 5.1 on 2024-11-13 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriTech', '0011_customuser_date_joined_customuser_last_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='price',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='agriculteur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('Légume', 'Légume'), ('Fruit', 'Fruit'), ('Céréale', 'Céréale')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='AgriTech.produit'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
