# Generated by Django 5.1 on 2024-11-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriTech', '0014_alter_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
